apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfc-static
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kfc-static
  template:
    metadata:
      labels:
        app: kfc-static
    spec:
      containers:
        - name: kfc-website
          image: hanif040/kfc-static:v2
          ports:
            - containerPort: 80

