apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfc-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kfc
  template:
    metadata:
      labels:
        app: kfc
    spec:
      containers:
      - name: kfc
        image: hanif040/kfc:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10

